{
    "ParentLink": {
        "Property": "to_CustomerSalesArea",
        "Target": {
            "EntitySet": "A_Customer",
            "ReadLink": "{@odata.readLink}"
        }
    },
    "OnFailure": "/BusinessPartner/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/BusinessPartner/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "Customer": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:Customer/#Value",
        "SalesOrganization": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:SalesOrganization/#Value",
        "DistributionChannel": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:DistributionChannel/#Value",
        "Division": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:Division/#Value",
        "AccountByCustomer": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:AccountByCustomer/#Value",
        "AuthorizationGroup": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:AuthorizationGroup/#Value",
        "BillingIsBlockedForCustomer": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:BillingIsBlockedForCustomer/#Value",
        "CompleteDeliveryIsDefined": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:CompleteDeliveryIsDefined/#Value",
        "CreditControlArea": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:CreditControlArea/#Value",
        "Currency": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:Currency/#Value",
        "CustIsRlvtForSettlmtMgmt": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:CustIsRlvtForSettlmtMgmt/#Value",
        "CustomerABCClassification": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:CustomerABCClassification/#Value",
        "CustomerAccountAssignmentGroup": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:CustomerAccountAssignmentGroup/#Value",
        "CustomerGroup": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:CustomerGroup/#Value",
        "CustomerIsRebateRelevant": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:CustomerIsRebateRelevant/#Value",
        "CustomerPaymentTerms": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:CustomerPaymentTerms/#Value",
        "CustomerPriceGroup": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:CustomerPriceGroup/#Value",
        "CustomerPricingProcedure": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:CustomerPricingProcedure/#Value",
        "CustomerStatisticsGroup": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:CustomerStatisticsGroup/#Value",
        "CustProdProposalProcedure": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:CustProdProposalProcedure/#Value",
        "DeliveryIsBlockedForCustomer": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:DeliveryIsBlockedForCustomer/#Value",
        "DeliveryPriority": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:DeliveryPriority/#Value",
        "IncotermsClassification": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:IncotermsClassification/#Value",
        "IncotermsLocation2": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:IncotermsLocation2/#Value",
        "IncotermsVersion": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:IncotermsVersion/#Value",
        "IncotermsLocation1": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:IncotermsLocation1/#Value",
        "DeletionIndicator": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:DeletionIndicator/#Value",
        "IncotermsTransferLocation": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:IncotermsTransferLocation/#Value",
        "InspSbstHasNoTimeOrQuantity": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:InspSbstHasNoTimeOrQuantity/#Value",
        "InvoiceDate": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:InvoiceDate/#Value",
        "ItemOrderProbabilityInPercent": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:ItemOrderProbabilityInPercent/#Value",
        "ManualInvoiceMaintIsRelevant": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:ManualInvoiceMaintIsRelevant/#Value",
        "MaxNmbrOfPartialDelivery": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:MaxNmbrOfPartialDelivery/#Value",
        "OrderCombinationIsAllowed": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:OrderCombinationIsAllowed/#Value",
        "OrderIsBlockedForCustomer": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:OrderIsBlockedForCustomer/#Value",
        "OverdelivTolrtdLmtRatioInPct": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:OverdelivTolrtdLmtRatioInPct/#Value",
        "PartialDeliveryIsAllowed": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:PartialDeliveryIsAllowed/#Value",
        "PriceListType": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:PriceListType/#Value",
        "ProductUnitGroup": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:ProductUnitGroup/#Value",
        "ProofOfDeliveryTimeValue": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:ProofOfDeliveryTimeValue/#Value",
        "SalesGroup": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:SalesGroup/#Value",
        "SalesItemProposal": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:SalesItemProposal/#Value",
        "SalesOffice": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:SalesOffice/#Value",
        "ShippingCondition": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:ShippingCondition/#Value",
        "SlsDocIsRlvtForProofOfDeliv": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:SlsDocIsRlvtForProofOfDeliv/#Value",
        "SlsUnlmtdOvrdelivIsAllwd": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:SlsUnlmtdOvrdelivIsAllwd/#Value",
        "SupplyingPlant": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:SupplyingPlant/#Value",
        "SalesDistrict": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:SalesDistrict/#Value",
        "UnderdelivTolrtdLmtRatioInPct": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:UnderdelivTolrtdLmtRatioInPct/#Value",
        "InvoiceListSchedule": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:InvoiceListSchedule/#Value",
        "ExchangeRateType": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:ExchangeRateType/#Value",
        "AdditionalCustomerGroup1": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:AdditionalCustomerGroup1/#Value",
        "AdditionalCustomerGroup2": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:AdditionalCustomerGroup2/#Value",
        "AdditionalCustomerGroup3": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:AdditionalCustomerGroup3/#Value",
        "AdditionalCustomerGroup4": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:AdditionalCustomerGroup4/#Value",
        "AdditionalCustomerGroup5": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:AdditionalCustomerGroup5/#Value",
        "PaymentGuaranteeProcedure": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:PaymentGuaranteeProcedure/#Value",
        "CustomerAccountGroup": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:CustomerAccountGroup/#Value",
        "YY1_PaymentMethod_csa": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:YY1_PaymentMethod_csa/#Value",
        "YY1_PaymentMethod_csaF": "#Page:A_Customer_CreateA_CustomerSalesAreaType/#Control:YY1_PaymentMethod_csaF/#Value"
    },
    "Target": {
        "EntitySet": "A_CustomerSalesArea",
        "Service": "/BusinessPartner/Services/Business_Partner.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateRelatedEntity"
}