{
    "CreateLinks": [],
    "OnFailure": "/BusinessPartner/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/BusinessPartner/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "Customer": "#Page:A_Customer_Create/#Control:Customer/#Value",
        "AuthorizationGroup": "#Page:A_Customer_Create/#Control:AuthorizationGroup/#Value",
        "BillingIsBlockedForCustomer": "#Page:A_Customer_Create/#Control:BillingIsBlockedForCustomer/#Value",
        "CreatedByUser": "#Page:A_Customer_Create/#Control:CreatedByUser/#Value",
        "CreationDate": "#Page:A_Customer_Create/#Control:CreationDate/#Value",
        "CustomerAccountGroup": "#Page:A_Customer_Create/#Control:CustomerAccountGroup/#Value",
        "CustomerClassification": "#Page:A_Customer_Create/#Control:CustomerClassification/#Value",
        "CustomerFullName": "#Page:A_Customer_Create/#Control:CustomerFullName/#Value",
        "BPCustomerFullName": "#Page:A_Customer_Create/#Control:BPCustomerFullName/#Value",
        "CustomerName": "#Page:A_Customer_Create/#Control:CustomerName/#Value",
        "BPCustomerName": "#Page:A_Customer_Create/#Control:BPCustomerName/#Value",
        "DeliveryIsBlocked": "#Page:A_Customer_Create/#Control:DeliveryIsBlocked/#Value",
        "FreeDefinedAttribute01": "#Page:A_Customer_Create/#Control:FreeDefinedAttribute01/#Value",
        "FreeDefinedAttribute02": "#Page:A_Customer_Create/#Control:FreeDefinedAttribute02/#Value",
        "FreeDefinedAttribute03": "#Page:A_Customer_Create/#Control:FreeDefinedAttribute03/#Value",
        "FreeDefinedAttribute04": "#Page:A_Customer_Create/#Control:FreeDefinedAttribute04/#Value",
        "FreeDefinedAttribute05": "#Page:A_Customer_Create/#Control:FreeDefinedAttribute05/#Value",
        "FreeDefinedAttribute06": "#Page:A_Customer_Create/#Control:FreeDefinedAttribute06/#Value",
        "FreeDefinedAttribute07": "#Page:A_Customer_Create/#Control:FreeDefinedAttribute07/#Value",
        "FreeDefinedAttribute08": "#Page:A_Customer_Create/#Control:FreeDefinedAttribute08/#Value",
        "FreeDefinedAttribute09": "#Page:A_Customer_Create/#Control:FreeDefinedAttribute09/#Value",
        "FreeDefinedAttribute10": "#Page:A_Customer_Create/#Control:FreeDefinedAttribute10/#Value",
        "NFPartnerIsNaturalPerson": "#Page:A_Customer_Create/#Control:NFPartnerIsNaturalPerson/#Value",
        "OrderIsBlockedForCustomer": "#Page:A_Customer_Create/#Control:OrderIsBlockedForCustomer/#Value",
        "PostingIsBlocked": "#Page:A_Customer_Create/#Control:PostingIsBlocked/#Value",
        "Supplier": "#Page:A_Customer_Create/#Control:Supplier/#Value",
        "CustomerCorporateGroup": "#Page:A_Customer_Create/#Control:CustomerCorporateGroup/#Value",
        "FiscalAddress": "#Page:A_Customer_Create/#Control:FiscalAddress/#Value",
        "Industry": "#Page:A_Customer_Create/#Control:Industry/#Value",
        "IndustryCode1": "#Page:A_Customer_Create/#Control:IndustryCode1/#Value",
        "IndustryCode2": "#Page:A_Customer_Create/#Control:IndustryCode2/#Value",
        "IndustryCode3": "#Page:A_Customer_Create/#Control:IndustryCode3/#Value",
        "IndustryCode4": "#Page:A_Customer_Create/#Control:IndustryCode4/#Value",
        "IndustryCode5": "#Page:A_Customer_Create/#Control:IndustryCode5/#Value",
        "InternationalLocationNumber1": "#Page:A_Customer_Create/#Control:InternationalLocationNumber1/#Value",
        "InternationalLocationNumber2": "#Page:A_Customer_Create/#Control:InternationalLocationNumber2/#Value",
        "InternationalLocationNumber3": "#Page:A_Customer_Create/#Control:InternationalLocationNumber3/#Value",
        "NielsenRegion": "#Page:A_Customer_Create/#Control:NielsenRegion/#Value",
        "PaymentReason": "#Page:A_Customer_Create/#Control:PaymentReason/#Value",
        "ResponsibleType": "#Page:A_Customer_Create/#Control:ResponsibleType/#Value",
        "TaxNumber1": "#Page:A_Customer_Create/#Control:TaxNumber1/#Value",
        "TaxNumber2": "#Page:A_Customer_Create/#Control:TaxNumber2/#Value",
        "TaxNumber3": "#Page:A_Customer_Create/#Control:TaxNumber3/#Value",
        "TaxNumber4": "#Page:A_Customer_Create/#Control:TaxNumber4/#Value",
        "TaxNumber5": "#Page:A_Customer_Create/#Control:TaxNumber5/#Value",
        "TaxNumberType": "#Page:A_Customer_Create/#Control:TaxNumberType/#Value",
        "VATRegistration": "#Page:A_Customer_Create/#Control:VATRegistration/#Value",
        "DeletionIndicator": "#Page:A_Customer_Create/#Control:DeletionIndicator/#Value",
        "ExpressTrainStationName": "#Page:A_Customer_Create/#Control:ExpressTrainStationName/#Value",
        "TrainStationName": "#Page:A_Customer_Create/#Control:TrainStationName/#Value",
        "CityCode": "#Page:A_Customer_Create/#Control:CityCode/#Value",
        "County": "#Page:A_Customer_Create/#Control:County/#Value",
        "BR_ICMSTaxPayerType": "#Page:A_Customer_Create/#Control:BR_ICMSTaxPayerType/#Value"
    },
    "Target": {
        "EntitySet": "A_Customer",
        "Service": "/BusinessPartner/Services/Business_Partner.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}