{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/BusinessPartner/Pages/Business_Partner_A_Customer/A_Customer_CreateA_CustAddrDepdntInformationType.page",
    "_Type": "Action.Type.Navigation"
}