{
    "ParentLink": {
        "Property": "to_SlsAreaAddrDepdntInfo",
        "Target": {
            "EntitySet": "A_CustomerSalesArea",
            "ReadLink": "{@odata.readLink}"
        }
    },
    "OnFailure": "/BusinessPartner/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/BusinessPartner/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "Customer": "#Page:A_CustomerSalesArea_CreateA_CustSlsAreaAddrDepdntInfoType/#Control:Customer/#Value",
        "SalesOrganization": "#Page:A_CustomerSalesArea_CreateA_CustSlsAreaAddrDepdntInfoType/#Control:SalesOrganization/#Value",
        "DistributionChannel": "#Page:A_CustomerSalesArea_CreateA_CustSlsAreaAddrDepdntInfoType/#Control:DistributionChannel/#Value",
        "Division": "#Page:A_CustomerSalesArea_CreateA_CustSlsAreaAddrDepdntInfoType/#Control:Division/#Value",
        "AddressID": "#Page:A_CustomerSalesArea_CreateA_CustSlsAreaAddrDepdntInfoType/#Control:AddressID/#Value",
        "IncotermsClassification": "#Page:A_CustomerSalesArea_CreateA_CustSlsAreaAddrDepdntInfoType/#Control:IncotermsClassification/#Value",
        "IncotermsLocation1": "#Page:A_CustomerSalesArea_CreateA_CustSlsAreaAddrDepdntInfoType/#Control:IncotermsLocation1/#Value",
        "IncotermsLocation2": "#Page:A_CustomerSalesArea_CreateA_CustSlsAreaAddrDepdntInfoType/#Control:IncotermsLocation2/#Value",
        "DeliveryIsBlocked": "#Page:A_CustomerSalesArea_CreateA_CustSlsAreaAddrDepdntInfoType/#Control:DeliveryIsBlocked/#Value",
        "SalesOffice": "#Page:A_CustomerSalesArea_CreateA_CustSlsAreaAddrDepdntInfoType/#Control:SalesOffice/#Value",
        "SalesGroup": "#Page:A_CustomerSalesArea_CreateA_CustSlsAreaAddrDepdntInfoType/#Control:SalesGroup/#Value",
        "ShippingCondition": "#Page:A_CustomerSalesArea_CreateA_CustSlsAreaAddrDepdntInfoType/#Control:ShippingCondition/#Value",
        "SupplyingPlant": "#Page:A_CustomerSalesArea_CreateA_CustSlsAreaAddrDepdntInfoType/#Control:SupplyingPlant/#Value",
        "IncotermsVersion": "#Page:A_CustomerSalesArea_CreateA_CustSlsAreaAddrDepdntInfoType/#Control:IncotermsVersion/#Value"
    },
    "Target": {
        "EntitySet": "A_CustSlsAreaAddrDepdntInfo",
        "Service": "/BusinessPartner/Services/Business_Partner.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateRelatedEntity"
}