{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/BusinessPartner/Pages/Business_Partner_A_CustomerSalesArea/A_CustomerSalesArea_CreateA_CustSalesPartnerFuncType.page",
    "_Type": "Action.Type.Navigation"
}