{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/BusinessPartner/Pages/Business_Partner_A_CustomerTaxGrouping/A_CustomerTaxGrouping_Edit.page",
    "_Type": "Action.Type.Navigation"
}