{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "A_BusinessPartnerTaxNumber",
        "Service": "/BusinessPartner/Services/Business_Partner.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "BusinessPartner": "#Page:A_BusinessPartnerTaxNumber_Edit/#Control:BusinessPartner/#Value",
        "BPTaxType": "#Page:A_BusinessPartnerTaxNumber_Edit/#Control:BPTaxType/#Value",
        "BPTaxNumber": "#Page:A_BusinessPartnerTaxNumber_Edit/#Control:BPTaxNumber/#Value",
        "BPTaxLongNumber": "#Page:A_BusinessPartnerTaxNumber_Edit/#Control:BPTaxLongNumber/#Value",
        "AuthorizationGroup": "#Page:A_BusinessPartnerTaxNumber_Edit/#Control:AuthorizationGroup/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/BusinessPartner/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/BusinessPartner/Actions/UpdateEntityFailureMessage.action"
}