{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/BusinessPartner/Pages/Business_Partner_A_BusinessPartnerBank/A_BusinessPartnerBank_Edit.page",
    "_Type": "Action.Type.Navigation"
}