{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "A_BPAddressIndependentPhone",
        "Service": "/BusinessPartner/Services/Business_Partner.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "BusinessPartner": "#Page:A_BPAddressIndependentPhone_Edit/#Control:BusinessPartner/#Value",
        "AddressID": "#Page:A_BPAddressIndependentPhone_Edit/#Control:AddressID/#Value",
        "Person": "#Page:A_BPAddressIndependentPhone_Edit/#Control:Person/#Value",
        "OrdinalNumber": "#Page:A_BPAddressIndependentPhone_Edit/#Control:OrdinalNumber/#Value",
        "DestinationLocationCountry": "#Page:A_BPAddressIndependentPhone_Edit/#Control:DestinationLocationCountry/#Value",
        "InternationalPhoneNumber": "#Page:A_BPAddressIndependentPhone_Edit/#Control:InternationalPhoneNumber/#Value",
        "IsDefaultPhoneNumber": "#Page:A_BPAddressIndependentPhone_Edit/#Control:IsDefaultPhoneNumber/#Value",
        "PhoneNumber": "#Page:A_BPAddressIndependentPhone_Edit/#Control:PhoneNumber/#Value",
        "PhoneNumberExtension": "#Page:A_BPAddressIndependentPhone_Edit/#Control:PhoneNumberExtension/#Value",
        "PhoneNumberType": "#Page:A_BPAddressIndependentPhone_Edit/#Control:PhoneNumberType/#Value",
        "ValidityStartDate": "#Page:A_BPAddressIndependentPhone_Edit/#Control:ValidityStartDate/#Value",
        "ValidityEndDate": "#Page:A_BPAddressIndependentPhone_Edit/#Control:ValidityEndDate/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/BusinessPartner/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/BusinessPartner/Actions/UpdateEntityFailureMessage.action"
}