{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/BusinessPartner/Pages/Business_Partner_A_BPAddressIndependentPhone/A_BPAddressIndependentPhone_Edit.page",
    "_Type": "Action.Type.Navigation"
}