{
	"_Type": "Action.Type.CheckBarcodeScannerPrerequisite",
	"OnFailure": "/BusinessPartner/Actions/BarcodeScanner/OpenBarcodeScanner.action",
	"OnSuccess": "/BusinessPartner/Actions/BarcodeScanner/OpenBarcodeScanner.action"
}