{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/BusinessPartner/Pages/Business_Partner_A_BusinessPartnerAlias/A_BusinessPartnerAlias_Edit.page",
    "_Type": "Action.Type.Navigation"
}