{
    "ParentLink": {
        "Property": "to_SupplierText",
        "Target": {
            "EntitySet": "A_Supplier",
            "ReadLink": "{@odata.readLink}"
        }
    },
    "OnFailure": "/BusinessPartner/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/BusinessPartner/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "Supplier": "#Page:A_Supplier_CreateA_SupplierTextType/#Control:Supplier/#Value",
        "Language": "#Page:A_Supplier_CreateA_SupplierTextType/#Control:Language/#Value",
        "LongTextID": "#Page:A_Supplier_CreateA_SupplierTextType/#Control:LongTextID/#Value",
        "LongText": "#Page:A_Supplier_CreateA_SupplierTextType/#Control:LongText/#Value"
    },
    "Target": {
        "EntitySet": "A_SupplierText",
        "Service": "/BusinessPartner/Services/Business_Partner.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateRelatedEntity"
}