{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "A_Supplier",
        "Service": "/BusinessPartner/Services/Business_Partner.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "Supplier": "#Page:A_Supplier_Edit/#Control:Supplier/#Value",
        "AlternativePayeeAccountNumber": "#Page:A_Supplier_Edit/#Control:AlternativePayeeAccountNumber/#Value",
        "AuthorizationGroup": "#Page:A_Supplier_Edit/#Control:AuthorizationGroup/#Value",
        "BusinessPartnerPanNumber": "#Page:A_Supplier_Edit/#Control:BusinessPartnerPanNumber/#Value",
        "CreatedByUser": "#Page:A_Supplier_Edit/#Control:CreatedByUser/#Value",
        "CreationDate": "#Page:A_Supplier_Edit/#Control:CreationDate/#Value",
        "Customer": "#Page:A_Supplier_Edit/#Control:Customer/#Value",
        "PaymentIsBlockedForSupplier": "#Page:A_Supplier_Edit/#Control:PaymentIsBlockedForSupplier/#Value",
        "PostingIsBlocked": "#Page:A_Supplier_Edit/#Control:PostingIsBlocked/#Value",
        "PurchasingIsBlocked": "#Page:A_Supplier_Edit/#Control:PurchasingIsBlocked/#Value",
        "SupplierAccountGroup": "#Page:A_Supplier_Edit/#Control:SupplierAccountGroup/#Value",
        "SupplierFullName": "#Page:A_Supplier_Edit/#Control:SupplierFullName/#Value",
        "SupplierName": "#Page:A_Supplier_Edit/#Control:SupplierName/#Value",
        "VATRegistration": "#Page:A_Supplier_Edit/#Control:VATRegistration/#Value",
        "BirthDate": "#Page:A_Supplier_Edit/#Control:BirthDate/#Value",
        "ConcatenatedInternationalLocNo": "#Page:A_Supplier_Edit/#Control:ConcatenatedInternationalLocNo/#Value",
        "DeletionIndicator": "#Page:A_Supplier_Edit/#Control:DeletionIndicator/#Value",
        "FiscalAddress": "#Page:A_Supplier_Edit/#Control:FiscalAddress/#Value",
        "Industry": "#Page:A_Supplier_Edit/#Control:Industry/#Value",
        "InternationalLocationNumber1": "#Page:A_Supplier_Edit/#Control:InternationalLocationNumber1/#Value",
        "InternationalLocationNumber2": "#Page:A_Supplier_Edit/#Control:InternationalLocationNumber2/#Value",
        "InternationalLocationNumber3": "#Page:A_Supplier_Edit/#Control:InternationalLocationNumber3/#Value",
        "IsNaturalPerson": "#Page:A_Supplier_Edit/#Control:IsNaturalPerson/#Value",
        "PaymentReason": "#Page:A_Supplier_Edit/#Control:PaymentReason/#Value",
        "ResponsibleType": "#Page:A_Supplier_Edit/#Control:ResponsibleType/#Value",
        "SuplrQltyInProcmtCertfnValidTo": "#Page:A_Supplier_Edit/#Control:SuplrQltyInProcmtCertfnValidTo/#Value",
        "SuplrQualityManagementSystem": "#Page:A_Supplier_Edit/#Control:SuplrQualityManagementSystem/#Value",
        "SupplierCorporateGroup": "#Page:A_Supplier_Edit/#Control:SupplierCorporateGroup/#Value",
        "SupplierProcurementBlock": "#Page:A_Supplier_Edit/#Control:SupplierProcurementBlock/#Value",
        "TaxNumber1": "#Page:A_Supplier_Edit/#Control:TaxNumber1/#Value",
        "TaxNumber2": "#Page:A_Supplier_Edit/#Control:TaxNumber2/#Value",
        "TaxNumber3": "#Page:A_Supplier_Edit/#Control:TaxNumber3/#Value",
        "TaxNumber4": "#Page:A_Supplier_Edit/#Control:TaxNumber4/#Value",
        "TaxNumber5": "#Page:A_Supplier_Edit/#Control:TaxNumber5/#Value",
        "TaxNumberResponsible": "#Page:A_Supplier_Edit/#Control:TaxNumberResponsible/#Value",
        "TaxNumberType": "#Page:A_Supplier_Edit/#Control:TaxNumberType/#Value",
        "SuplrProofOfDelivRlvtCode": "#Page:A_Supplier_Edit/#Control:SuplrProofOfDelivRlvtCode/#Value",
        "BR_TaxIsSplit": "#Page:A_Supplier_Edit/#Control:BR_TaxIsSplit/#Value",
        "DataExchangeInstructionKey": "#Page:A_Supplier_Edit/#Control:DataExchangeInstructionKey/#Value",
        "JP_SuplrAmtInCapitalAmount": "#Page:A_Supplier_Edit/#Control:JP_SuplrAmtInCapitalAmount/#Value",
        "JP_SupplierCapitalAmountCrcy": "#Page:A_Supplier_Edit/#Control:JP_SupplierCapitalAmountCrcy/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/BusinessPartner/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/BusinessPartner/Actions/UpdateEntityFailureMessage.action"
}