{
    "CreateLinks": [],
    "OnFailure": "/BusinessPartner/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/BusinessPartner/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "Supplier": "#Page:A_Supplier_Create/#Control:Supplier/#Value",
        "AlternativePayeeAccountNumber": "#Page:A_Supplier_Create/#Control:AlternativePayeeAccountNumber/#Value",
        "AuthorizationGroup": "#Page:A_Supplier_Create/#Control:AuthorizationGroup/#Value",
        "BusinessPartnerPanNumber": "#Page:A_Supplier_Create/#Control:BusinessPartnerPanNumber/#Value",
        "CreatedByUser": "#Page:A_Supplier_Create/#Control:CreatedByUser/#Value",
        "CreationDate": "#Page:A_Supplier_Create/#Control:CreationDate/#Value",
        "Customer": "#Page:A_Supplier_Create/#Control:Customer/#Value",
        "PaymentIsBlockedForSupplier": "#Page:A_Supplier_Create/#Control:PaymentIsBlockedForSupplier/#Value",
        "PostingIsBlocked": "#Page:A_Supplier_Create/#Control:PostingIsBlocked/#Value",
        "PurchasingIsBlocked": "#Page:A_Supplier_Create/#Control:PurchasingIsBlocked/#Value",
        "SupplierAccountGroup": "#Page:A_Supplier_Create/#Control:SupplierAccountGroup/#Value",
        "SupplierFullName": "#Page:A_Supplier_Create/#Control:SupplierFullName/#Value",
        "SupplierName": "#Page:A_Supplier_Create/#Control:SupplierName/#Value",
        "VATRegistration": "#Page:A_Supplier_Create/#Control:VATRegistration/#Value",
        "BirthDate": "#Page:A_Supplier_Create/#Control:BirthDate/#Value",
        "ConcatenatedInternationalLocNo": "#Page:A_Supplier_Create/#Control:ConcatenatedInternationalLocNo/#Value",
        "DeletionIndicator": "#Page:A_Supplier_Create/#Control:DeletionIndicator/#Value",
        "FiscalAddress": "#Page:A_Supplier_Create/#Control:FiscalAddress/#Value",
        "Industry": "#Page:A_Supplier_Create/#Control:Industry/#Value",
        "InternationalLocationNumber1": "#Page:A_Supplier_Create/#Control:InternationalLocationNumber1/#Value",
        "InternationalLocationNumber2": "#Page:A_Supplier_Create/#Control:InternationalLocationNumber2/#Value",
        "InternationalLocationNumber3": "#Page:A_Supplier_Create/#Control:InternationalLocationNumber3/#Value",
        "IsNaturalPerson": "#Page:A_Supplier_Create/#Control:IsNaturalPerson/#Value",
        "PaymentReason": "#Page:A_Supplier_Create/#Control:PaymentReason/#Value",
        "ResponsibleType": "#Page:A_Supplier_Create/#Control:ResponsibleType/#Value",
        "SuplrQltyInProcmtCertfnValidTo": "#Page:A_Supplier_Create/#Control:SuplrQltyInProcmtCertfnValidTo/#Value",
        "SuplrQualityManagementSystem": "#Page:A_Supplier_Create/#Control:SuplrQualityManagementSystem/#Value",
        "SupplierCorporateGroup": "#Page:A_Supplier_Create/#Control:SupplierCorporateGroup/#Value",
        "SupplierProcurementBlock": "#Page:A_Supplier_Create/#Control:SupplierProcurementBlock/#Value",
        "TaxNumber1": "#Page:A_Supplier_Create/#Control:TaxNumber1/#Value",
        "TaxNumber2": "#Page:A_Supplier_Create/#Control:TaxNumber2/#Value",
        "TaxNumber3": "#Page:A_Supplier_Create/#Control:TaxNumber3/#Value",
        "TaxNumber4": "#Page:A_Supplier_Create/#Control:TaxNumber4/#Value",
        "TaxNumber5": "#Page:A_Supplier_Create/#Control:TaxNumber5/#Value",
        "TaxNumberResponsible": "#Page:A_Supplier_Create/#Control:TaxNumberResponsible/#Value",
        "TaxNumberType": "#Page:A_Supplier_Create/#Control:TaxNumberType/#Value",
        "SuplrProofOfDelivRlvtCode": "#Page:A_Supplier_Create/#Control:SuplrProofOfDelivRlvtCode/#Value",
        "BR_TaxIsSplit": "#Page:A_Supplier_Create/#Control:BR_TaxIsSplit/#Value",
        "DataExchangeInstructionKey": "#Page:A_Supplier_Create/#Control:DataExchangeInstructionKey/#Value",
        "JP_SuplrAmtInCapitalAmount": "#Page:A_Supplier_Create/#Control:JP_SuplrAmtInCapitalAmount/#Value",
        "JP_SupplierCapitalAmountCrcy": "#Page:A_Supplier_Create/#Control:JP_SupplierCapitalAmountCrcy/#Value"
    },
    "Target": {
        "EntitySet": "A_Supplier",
        "Service": "/BusinessPartner/Services/Business_Partner.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}