{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/BusinessPartner/Pages/Business_Partner_A_Supplier/A_Supplier_CreateA_SupplierCompanyType.page",
    "_Type": "Action.Type.Navigation"
}