{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "A_SupplierCompany",
        "Service": "/BusinessPartner/Services/Business_Partner.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "Supplier": "#Page:A_SupplierCompany_Edit/#Control:Supplier/#Value",
        "CompanyCode": "#Page:A_SupplierCompany_Edit/#Control:CompanyCode/#Value",
        "AuthorizationGroup": "#Page:A_SupplierCompany_Edit/#Control:AuthorizationGroup/#Value",
        "CompanyCodeName": "#Page:A_SupplierCompany_Edit/#Control:CompanyCodeName/#Value",
        "PaymentBlockingReason": "#Page:A_SupplierCompany_Edit/#Control:PaymentBlockingReason/#Value",
        "SupplierIsBlockedForPosting": "#Page:A_SupplierCompany_Edit/#Control:SupplierIsBlockedForPosting/#Value",
        "AccountingClerk": "#Page:A_SupplierCompany_Edit/#Control:AccountingClerk/#Value",
        "AccountingClerkFaxNumber": "#Page:A_SupplierCompany_Edit/#Control:AccountingClerkFaxNumber/#Value",
        "AccountingClerkPhoneNumber": "#Page:A_SupplierCompany_Edit/#Control:AccountingClerkPhoneNumber/#Value",
        "SupplierClerk": "#Page:A_SupplierCompany_Edit/#Control:SupplierClerk/#Value",
        "SupplierClerkURL": "#Page:A_SupplierCompany_Edit/#Control:SupplierClerkURL/#Value",
        "PaymentMethodsList": "#Page:A_SupplierCompany_Edit/#Control:PaymentMethodsList/#Value",
        "PaymentReason": "#Page:A_SupplierCompany_Edit/#Control:PaymentReason/#Value",
        "PaymentTerms": "#Page:A_SupplierCompany_Edit/#Control:PaymentTerms/#Value",
        "ClearCustomerSupplier": "#Page:A_SupplierCompany_Edit/#Control:ClearCustomerSupplier/#Value",
        "IsToBeLocallyProcessed": "#Page:A_SupplierCompany_Edit/#Control:IsToBeLocallyProcessed/#Value",
        "ItemIsToBePaidSeparately": "#Page:A_SupplierCompany_Edit/#Control:ItemIsToBePaidSeparately/#Value",
        "PaymentIsToBeSentByEDI": "#Page:A_SupplierCompany_Edit/#Control:PaymentIsToBeSentByEDI/#Value",
        "HouseBank": "#Page:A_SupplierCompany_Edit/#Control:HouseBank/#Value",
        "CheckPaidDurationInDays": "#Page:A_SupplierCompany_Edit/#Control:CheckPaidDurationInDays/#Value",
        "Currency": "#Page:A_SupplierCompany_Edit/#Control:Currency/#Value",
        "BillOfExchLmtAmtInCoCodeCrcy": "#Page:A_SupplierCompany_Edit/#Control:BillOfExchLmtAmtInCoCodeCrcy/#Value",
        "SupplierClerkIDBySupplier": "#Page:A_SupplierCompany_Edit/#Control:SupplierClerkIDBySupplier/#Value",
        "ReconciliationAccount": "#Page:A_SupplierCompany_Edit/#Control:ReconciliationAccount/#Value",
        "InterestCalculationCode": "#Page:A_SupplierCompany_Edit/#Control:InterestCalculationCode/#Value",
        "InterestCalculationDate": "#Page:A_SupplierCompany_Edit/#Control:InterestCalculationDate/#Value",
        "IntrstCalcFrequencyInMonths": "#Page:A_SupplierCompany_Edit/#Control:IntrstCalcFrequencyInMonths/#Value",
        "SupplierHeadOffice": "#Page:A_SupplierCompany_Edit/#Control:SupplierHeadOffice/#Value",
        "AlternativePayee": "#Page:A_SupplierCompany_Edit/#Control:AlternativePayee/#Value",
        "LayoutSortingRule": "#Page:A_SupplierCompany_Edit/#Control:LayoutSortingRule/#Value",
        "APARToleranceGroup": "#Page:A_SupplierCompany_Edit/#Control:APARToleranceGroup/#Value",
        "SupplierCertificationDate": "#Page:A_SupplierCompany_Edit/#Control:SupplierCertificationDate/#Value",
        "SupplierAccountNote": "#Page:A_SupplierCompany_Edit/#Control:SupplierAccountNote/#Value",
        "WithholdingTaxCountry": "#Page:A_SupplierCompany_Edit/#Control:WithholdingTaxCountry/#Value",
        "DeletionIndicator": "#Page:A_SupplierCompany_Edit/#Control:DeletionIndicator/#Value",
        "CashPlanningGroup": "#Page:A_SupplierCompany_Edit/#Control:CashPlanningGroup/#Value",
        "IsToBeCheckedForDuplicates": "#Page:A_SupplierCompany_Edit/#Control:IsToBeCheckedForDuplicates/#Value",
        "MinorityGroup": "#Page:A_SupplierCompany_Edit/#Control:MinorityGroup/#Value",
        "CreditMemoPaymentTerms": "#Page:A_SupplierCompany_Edit/#Control:CreditMemoPaymentTerms/#Value",
        "SupplierAccountGroup": "#Page:A_SupplierCompany_Edit/#Control:SupplierAccountGroup/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/BusinessPartner/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/BusinessPartner/Actions/UpdateEntityFailureMessage.action"
}