{
    "ParentLink": {
        "Property": "to_CompanyText",
        "Target": {
            "EntitySet": "A_SupplierCompany",
            "ReadLink": "{@odata.readLink}"
        }
    },
    "OnFailure": "/BusinessPartner/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/BusinessPartner/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "Supplier": "#Page:A_SupplierCompany_CreateA_SupplierCompanyTextType/#Control:Supplier/#Value",
        "CompanyCode": "#Page:A_SupplierCompany_CreateA_SupplierCompanyTextType/#Control:CompanyCode/#Value",
        "Language": "#Page:A_SupplierCompany_CreateA_SupplierCompanyTextType/#Control:Language/#Value",
        "LongTextID": "#Page:A_SupplierCompany_CreateA_SupplierCompanyTextType/#Control:LongTextID/#Value",
        "LongText": "#Page:A_SupplierCompany_CreateA_SupplierCompanyTextType/#Control:LongText/#Value"
    },
    "Target": {
        "EntitySet": "A_SupplierCompanyText",
        "Service": "/BusinessPartner/Services/Business_Partner.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateRelatedEntity"
}