{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/BusinessPartner/Pages/Business_Partner_A_BPRelationship/A_BPRelationship_Edit.page",
    "_Type": "Action.Type.Navigation"
}