{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/BusinessPartner/Pages/Business_Partner_A_CustAddrDepdntExtIdentifier/A_CustAddrDepdntExtIdentifier_Edit.page",
    "_Type": "Action.Type.Navigation"
}