{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "A_BPAddressIndependentEmail",
        "Service": "/BusinessPartner/Services/Business_Partner.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "BusinessPartner": "#Page:A_BPAddressIndependentEmail_Edit/#Control:BusinessPartner/#Value",
        "AddressID": "#Page:A_BPAddressIndependentEmail_Edit/#Control:AddressID/#Value",
        "Person": "#Page:A_BPAddressIndependentEmail_Edit/#Control:Person/#Value",
        "OrdinalNumber": "#Page:A_BPAddressIndependentEmail_Edit/#Control:OrdinalNumber/#Value",
        "EmailAddress": "#Page:A_BPAddressIndependentEmail_Edit/#Control:EmailAddress/#Value",
        "IsDefaultEmailAddress": "#Page:A_BPAddressIndependentEmail_Edit/#Control:IsDefaultEmailAddress/#Value",
        "ValidityStartDate": "#Page:A_BPAddressIndependentEmail_Edit/#Control:ValidityStartDate/#Value",
        "ValidityEndDate": "#Page:A_BPAddressIndependentEmail_Edit/#Control:ValidityEndDate/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/BusinessPartner/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/BusinessPartner/Actions/UpdateEntityFailureMessage.action"
}