{
    "ParentLink": {
        "Property": "to_BPDataController",
        "Target": {
            "EntitySet": "A_BusinessPartner",
            "ReadLink": "{@odata.readLink}"
        }
    },
    "OnFailure": "/BusinessPartner/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/BusinessPartner/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "BusinessPartner": "#Page:A_BusinessPartner_CreateA_BPDataControllerType/#Control:BusinessPartner/#Value",
        "DataController": "#Page:A_BusinessPartner_CreateA_BPDataControllerType/#Control:DataController/#Value",
        "PurposeForPersonalData": "#Page:A_BusinessPartner_CreateA_BPDataControllerType/#Control:PurposeForPersonalData/#Value",
        "DataControlAssignmentStatus": "#Page:A_BusinessPartner_CreateA_BPDataControllerType/#Control:DataControlAssignmentStatus/#Value",
        "BPDataControllerIsDerived": "#Page:A_BusinessPartner_CreateA_BPDataControllerType/#Control:BPDataControllerIsDerived/#Value",
        "PurposeDerived": "#Page:A_BusinessPartner_CreateA_BPDataControllerType/#Control:PurposeDerived/#Value",
        "PurposeType": "#Page:A_BusinessPartner_CreateA_BPDataControllerType/#Control:PurposeType/#Value",
        "BusinessPurposeFlag": "#Page:A_BusinessPartner_CreateA_BPDataControllerType/#Control:BusinessPurposeFlag/#Value"
    },
    "Target": {
        "EntitySet": "A_BPDataController",
        "Service": "/BusinessPartner/Services/Business_Partner.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateRelatedEntity"
}