{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "A_BusinessPartner",
        "Service": "/BusinessPartner/Services/Business_Partner.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "BusinessPartner": "#Page:A_BusinessPartner_Edit/#Control:BusinessPartner/#Value",
        "Customer": "#Page:A_BusinessPartner_Edit/#Control:Customer/#Value",
        "Supplier": "#Page:A_BusinessPartner_Edit/#Control:Supplier/#Value",
        "AcademicTitle": "#Page:A_BusinessPartner_Edit/#Control:AcademicTitle/#Value",
        "AuthorizationGroup": "#Page:A_BusinessPartner_Edit/#Control:AuthorizationGroup/#Value",
        "BusinessPartnerCategory": "#Page:A_BusinessPartner_Edit/#Control:BusinessPartnerCategory/#Value",
        "BusinessPartnerFullName": "#Page:A_BusinessPartner_Edit/#Control:BusinessPartnerFullName/#Value",
        "BusinessPartnerGrouping": "#Page:A_BusinessPartner_Edit/#Control:BusinessPartnerGrouping/#Value",
        "BusinessPartnerName": "#Page:A_BusinessPartner_Edit/#Control:BusinessPartnerName/#Value",
        "CorrespondenceLanguage": "#Page:A_BusinessPartner_Edit/#Control:CorrespondenceLanguage/#Value",
        "CreatedByUser": "#Page:A_BusinessPartner_Edit/#Control:CreatedByUser/#Value",
        "CreationDate": "#Page:A_BusinessPartner_Edit/#Control:CreationDate/#Value",
        "CreationTime": "#Page:A_BusinessPartner_Edit/#Control:CreationTime/#Value",
        "FirstName": "#Page:A_BusinessPartner_Edit/#Control:FirstName/#Value",
        "FormOfAddress": "#Page:A_BusinessPartner_Edit/#Control:FormOfAddress/#Value",
        "Industry": "#Page:A_BusinessPartner_Edit/#Control:Industry/#Value",
        "InternationalLocationNumber1": "#Page:A_BusinessPartner_Edit/#Control:InternationalLocationNumber1/#Value",
        "InternationalLocationNumber2": "#Page:A_BusinessPartner_Edit/#Control:InternationalLocationNumber2/#Value",
        "IsFemale": "#Page:A_BusinessPartner_Edit/#Control:IsFemale/#Value",
        "IsMale": "#Page:A_BusinessPartner_Edit/#Control:IsMale/#Value",
        "IsNaturalPerson": "#Page:A_BusinessPartner_Edit/#Control:IsNaturalPerson/#Value",
        "IsSexUnknown": "#Page:A_BusinessPartner_Edit/#Control:IsSexUnknown/#Value",
        "GenderCodeName": "#Page:A_BusinessPartner_Edit/#Control:GenderCodeName/#Value",
        "Language": "#Page:A_BusinessPartner_Edit/#Control:Language/#Value",
        "LastChangeDate": "#Page:A_BusinessPartner_Edit/#Control:LastChangeDate/#Value",
        "LastChangeTime": "#Page:A_BusinessPartner_Edit/#Control:LastChangeTime/#Value",
        "LastChangedByUser": "#Page:A_BusinessPartner_Edit/#Control:LastChangedByUser/#Value",
        "LastName": "#Page:A_BusinessPartner_Edit/#Control:LastName/#Value",
        "LegalForm": "#Page:A_BusinessPartner_Edit/#Control:LegalForm/#Value",
        "OrganizationBPName1": "#Page:A_BusinessPartner_Edit/#Control:OrganizationBPName1/#Value",
        "OrganizationBPName2": "#Page:A_BusinessPartner_Edit/#Control:OrganizationBPName2/#Value",
        "OrganizationBPName3": "#Page:A_BusinessPartner_Edit/#Control:OrganizationBPName3/#Value",
        "OrganizationBPName4": "#Page:A_BusinessPartner_Edit/#Control:OrganizationBPName4/#Value",
        "OrganizationFoundationDate": "#Page:A_BusinessPartner_Edit/#Control:OrganizationFoundationDate/#Value",
        "OrganizationLiquidationDate": "#Page:A_BusinessPartner_Edit/#Control:OrganizationLiquidationDate/#Value",
        "SearchTerm1": "#Page:A_BusinessPartner_Edit/#Control:SearchTerm1/#Value",
        "SearchTerm2": "#Page:A_BusinessPartner_Edit/#Control:SearchTerm2/#Value",
        "AdditionalLastName": "#Page:A_BusinessPartner_Edit/#Control:AdditionalLastName/#Value",
        "BirthDate": "#Page:A_BusinessPartner_Edit/#Control:BirthDate/#Value",
        "BusinessPartnerBirthDateStatus": "#Page:A_BusinessPartner_Edit/#Control:BusinessPartnerBirthDateStatus/#Value",
        "BusinessPartnerBirthplaceName": "#Page:A_BusinessPartner_Edit/#Control:BusinessPartnerBirthplaceName/#Value",
        "BusinessPartnerDeathDate": "#Page:A_BusinessPartner_Edit/#Control:BusinessPartnerDeathDate/#Value",
        "BusinessPartnerIsBlocked": "#Page:A_BusinessPartner_Edit/#Control:BusinessPartnerIsBlocked/#Value",
        "BusinessPartnerType": "#Page:A_BusinessPartner_Edit/#Control:BusinessPartnerType/#Value",
        "ETag": "#Page:A_BusinessPartner_Edit/#Control:ETag/#Value",
        "GroupBusinessPartnerName1": "#Page:A_BusinessPartner_Edit/#Control:GroupBusinessPartnerName1/#Value",
        "GroupBusinessPartnerName2": "#Page:A_BusinessPartner_Edit/#Control:GroupBusinessPartnerName2/#Value",
        "IndependentAddressID": "#Page:A_BusinessPartner_Edit/#Control:IndependentAddressID/#Value",
        "InternationalLocationNumber3": "#Page:A_BusinessPartner_Edit/#Control:InternationalLocationNumber3/#Value",
        "MiddleName": "#Page:A_BusinessPartner_Edit/#Control:MiddleName/#Value",
        "NameCountry": "#Page:A_BusinessPartner_Edit/#Control:NameCountry/#Value",
        "NameFormat": "#Page:A_BusinessPartner_Edit/#Control:NameFormat/#Value",
        "PersonFullName": "#Page:A_BusinessPartner_Edit/#Control:PersonFullName/#Value",
        "PersonNumber": "#Page:A_BusinessPartner_Edit/#Control:PersonNumber/#Value",
        "IsMarkedForArchiving": "#Page:A_BusinessPartner_Edit/#Control:IsMarkedForArchiving/#Value",
        "BusinessPartnerIDByExtSystem": "#Page:A_BusinessPartner_Edit/#Control:BusinessPartnerIDByExtSystem/#Value",
        "BusinessPartnerPrintFormat": "#Page:A_BusinessPartner_Edit/#Control:BusinessPartnerPrintFormat/#Value",
        "BusinessPartnerOccupation": "#Page:A_BusinessPartner_Edit/#Control:BusinessPartnerOccupation/#Value",
        "BusPartMaritalStatus": "#Page:A_BusinessPartner_Edit/#Control:BusPartMaritalStatus/#Value",
        "BusPartNationality": "#Page:A_BusinessPartner_Edit/#Control:BusPartNationality/#Value",
        "BusinessPartnerBirthName": "#Page:A_BusinessPartner_Edit/#Control:BusinessPartnerBirthName/#Value",
        "BusinessPartnerSupplementName": "#Page:A_BusinessPartner_Edit/#Control:BusinessPartnerSupplementName/#Value",
        "NaturalPersonEmployerName": "#Page:A_BusinessPartner_Edit/#Control:NaturalPersonEmployerName/#Value",
        "LastNamePrefix": "#Page:A_BusinessPartner_Edit/#Control:LastNamePrefix/#Value",
        "LastNameSecondPrefix": "#Page:A_BusinessPartner_Edit/#Control:LastNameSecondPrefix/#Value",
        "Initials": "#Page:A_BusinessPartner_Edit/#Control:Initials/#Value",
        "BPDataControllerIsNotRequired": "#Page:A_BusinessPartner_Edit/#Control:BPDataControllerIsNotRequired/#Value",
        "TradingPartner": "#Page:A_BusinessPartner_Edit/#Control:TradingPartner/#Value",
        "YY1_CityREMAX_bus": "#Page:A_BusinessPartner_Edit/#Control:YY1_CityREMAX_bus/#Value",
        "YY1_CCEmail_bus": "#Page:A_BusinessPartner_Edit/#Control:YY1_CCEmail_bus/#Value",
        "YY1_Text_bus": "#Page:A_BusinessPartner_Edit/#Control:YY1_Text_bus/#Value",
        "YY1_CCEmail_busF": "#Page:A_BusinessPartner_Edit/#Control:YY1_CCEmail_busF/#Value",
        "YY1_CityREMAX_busF": "#Page:A_BusinessPartner_Edit/#Control:YY1_CityREMAX_busF/#Value",
        "YY1_CityREMAX_busT": "#Page:A_BusinessPartner_Edit/#Control:YY1_CityREMAX_busT/#Value",
        "YY1_Text_busF": "#Page:A_BusinessPartner_Edit/#Control:YY1_Text_busF/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/BusinessPartner/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/BusinessPartner/Actions/UpdateEntityFailureMessage.action"
}