{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/BusinessPartner/Pages/Business_Partner_A_BusinessPartner/A_BusinessPartner_CreateA_BPAddressIndependentFaxType.page",
    "_Type": "Action.Type.Navigation"
}