{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/BusinessPartner/Pages/Business_Partner_A_BusinessPartnerAddress/A_BusinessPartnerAddress_CreateA_BuPaAddressUsageType.page",
    "_Type": "Action.Type.Navigation"
}