{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "A_SupplierPurchasingOrg",
        "Service": "/BusinessPartner/Services/Business_Partner.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "Supplier": "#Page:A_SupplierPurchasingOrg_Edit/#Control:Supplier/#Value",
        "PurchasingOrganization": "#Page:A_SupplierPurchasingOrg_Edit/#Control:PurchasingOrganization/#Value",
        "AutomaticEvaluatedRcptSettlmt": "#Page:A_SupplierPurchasingOrg_Edit/#Control:AutomaticEvaluatedRcptSettlmt/#Value",
        "CalculationSchemaGroupCode": "#Page:A_SupplierPurchasingOrg_Edit/#Control:CalculationSchemaGroupCode/#Value",
        "DeletionIndicator": "#Page:A_SupplierPurchasingOrg_Edit/#Control:DeletionIndicator/#Value",
        "EvaldReceiptSettlementIsActive": "#Page:A_SupplierPurchasingOrg_Edit/#Control:EvaldReceiptSettlementIsActive/#Value",
        "IncotermsClassification": "#Page:A_SupplierPurchasingOrg_Edit/#Control:IncotermsClassification/#Value",
        "IncotermsTransferLocation": "#Page:A_SupplierPurchasingOrg_Edit/#Control:IncotermsTransferLocation/#Value",
        "IncotermsVersion": "#Page:A_SupplierPurchasingOrg_Edit/#Control:IncotermsVersion/#Value",
        "IncotermsLocation1": "#Page:A_SupplierPurchasingOrg_Edit/#Control:IncotermsLocation1/#Value",
        "IncotermsLocation2": "#Page:A_SupplierPurchasingOrg_Edit/#Control:IncotermsLocation2/#Value",
        "IntrastatCrsBorderTrMode": "#Page:A_SupplierPurchasingOrg_Edit/#Control:IntrastatCrsBorderTrMode/#Value",
        "InvoiceIsGoodsReceiptBased": "#Page:A_SupplierPurchasingOrg_Edit/#Control:InvoiceIsGoodsReceiptBased/#Value",
        "InvoiceIsMMServiceEntryBased": "#Page:A_SupplierPurchasingOrg_Edit/#Control:InvoiceIsMMServiceEntryBased/#Value",
        "MaterialPlannedDeliveryDurn": "#Page:A_SupplierPurchasingOrg_Edit/#Control:MaterialPlannedDeliveryDurn/#Value",
        "MinimumOrderAmount": "#Page:A_SupplierPurchasingOrg_Edit/#Control:MinimumOrderAmount/#Value",
        "PaymentTerms": "#Page:A_SupplierPurchasingOrg_Edit/#Control:PaymentTerms/#Value",
        "PlanningCycle": "#Page:A_SupplierPurchasingOrg_Edit/#Control:PlanningCycle/#Value",
        "PricingDateControl": "#Page:A_SupplierPurchasingOrg_Edit/#Control:PricingDateControl/#Value",
        "ProdStockAndSlsDataTransfPrfl": "#Page:A_SupplierPurchasingOrg_Edit/#Control:ProdStockAndSlsDataTransfPrfl/#Value",
        "ProductUnitGroup": "#Page:A_SupplierPurchasingOrg_Edit/#Control:ProductUnitGroup/#Value",
        "PurOrdAutoGenerationIsAllowed": "#Page:A_SupplierPurchasingOrg_Edit/#Control:PurOrdAutoGenerationIsAllowed/#Value",
        "PurchaseOrderCurrency": "#Page:A_SupplierPurchasingOrg_Edit/#Control:PurchaseOrderCurrency/#Value",
        "PurchasingGroup": "#Page:A_SupplierPurchasingOrg_Edit/#Control:PurchasingGroup/#Value",
        "PurchasingIsBlockedForSupplier": "#Page:A_SupplierPurchasingOrg_Edit/#Control:PurchasingIsBlockedForSupplier/#Value",
        "RoundingProfile": "#Page:A_SupplierPurchasingOrg_Edit/#Control:RoundingProfile/#Value",
        "ShippingCondition": "#Page:A_SupplierPurchasingOrg_Edit/#Control:ShippingCondition/#Value",
        "SuplrDiscountInKindIsGranted": "#Page:A_SupplierPurchasingOrg_Edit/#Control:SuplrDiscountInKindIsGranted/#Value",
        "SuplrInvcRevalIsAllowed": "#Page:A_SupplierPurchasingOrg_Edit/#Control:SuplrInvcRevalIsAllowed/#Value",
        "SuplrIsRlvtForSettlmtMgmt": "#Page:A_SupplierPurchasingOrg_Edit/#Control:SuplrIsRlvtForSettlmtMgmt/#Value",
        "SuplrPurgOrgIsRlvtForPriceDetn": "#Page:A_SupplierPurchasingOrg_Edit/#Control:SuplrPurgOrgIsRlvtForPriceDetn/#Value",
        "SupplierABCClassificationCode": "#Page:A_SupplierPurchasingOrg_Edit/#Control:SupplierABCClassificationCode/#Value",
        "SupplierAccountNumber": "#Page:A_SupplierPurchasingOrg_Edit/#Control:SupplierAccountNumber/#Value",
        "SupplierIsReturnsSupplier": "#Page:A_SupplierPurchasingOrg_Edit/#Control:SupplierIsReturnsSupplier/#Value",
        "SupplierPhoneNumber": "#Page:A_SupplierPurchasingOrg_Edit/#Control:SupplierPhoneNumber/#Value",
        "SupplierRespSalesPersonName": "#Page:A_SupplierPurchasingOrg_Edit/#Control:SupplierRespSalesPersonName/#Value",
        "SupplierConfirmationControlKey": "#Page:A_SupplierPurchasingOrg_Edit/#Control:SupplierConfirmationControlKey/#Value",
        "IsOrderAcknRqd": "#Page:A_SupplierPurchasingOrg_Edit/#Control:IsOrderAcknRqd/#Value",
        "AuthorizationGroup": "#Page:A_SupplierPurchasingOrg_Edit/#Control:AuthorizationGroup/#Value",
        "SupplierAccountGroup": "#Page:A_SupplierPurchasingOrg_Edit/#Control:SupplierAccountGroup/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/BusinessPartner/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/BusinessPartner/Actions/UpdateEntityFailureMessage.action"
}