{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/BusinessPartner/Pages/Business_Partner_A_CustomerUnloadingPoint/A_CustomerUnloadingPoint_Edit.page",
    "_Type": "Action.Type.Navigation"
}