{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/BusinessPartner/Pages/Business_Partner_A_CustomerCompany/A_CustomerCompany_Edit.page",
    "_Type": "Action.Type.Navigation"
}