{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/BusinessPartner/Pages/Business_Partner_A_BusPartAddrDepdntTaxNmbr/A_BusPartAddrDepdntTaxNmbr_Edit.page",
    "_Type": "Action.Type.Navigation"
}