{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/BusinessPartner/Pages/Business_Partner_A_BPFiscalYearInformation/A_BPFiscalYearInformation_Edit.page",
    "_Type": "Action.Type.Navigation"
}