{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/BusinessPartner/Pages/Business_Partner_A_BusinessPartnerRole/A_BusinessPartnerRole_Edit.page",
    "_Type": "Action.Type.Navigation"
}